### ISSUE TITLE
Only black color work

### ISSUE THREAD

**Issue by LoorZix** [Seconb/Roblox-Colorbot#35]
i've been using version 9 before and it worked perfectly, i stopped cheating and now i wanted to retry but now, i can only use black color , other colors just don't focus enemies. Can you help bcs black is rlly bad and focus on everything.
Im using it on arsenal

**Comment by Seconb** [comment]
think before u post just update it

arsenal changed the enemy color slightly so i had to update it to fix that

**Comment by LoorZix** [comment]
> think before u post just update it
> 
> arsenal changed the enemy color slightly so i had to update it to fix that

Bruh, i use last version il not dumb
